<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            $(function() {
                $("input[id$='merchant_gateway_id']").on('change', function () {
                    var merchant_id = $(this).val();
                    var length_id = merchant_id.length;
                    if (length_id > 2) {
                        $.ajax ({
                            url: '<?php echo $this->getAjaxUrl() ?>',
                            showLoader: true,
                            data: {merchant:merchant_id, type:'merchant'},
                            type: "POST",
                            success: function(result) {
                                $("select[id$='gateway_supported_coins']").html('');
                                $("input[id$='merchant_gateway_id']").css('border','1px solid #adadad');
                                $('.incorrect-merchant').remove();
                                if (result.length) {
                                    $.each(result, function () {
                                        $("select[id$='gateway_supported_coins']").append('<option value="'+this.value+'">'+this.title+'</option>');
                                    });
                                } else {
                                    $("input[id$='merchant_gateway_id']").css('border','1px solid red');
                                    $("input[id$='merchant_gateway_id']").closest('td').append('<span style="color:red" class="incorrect-merchant">MerchantID should be type Integer, please correct. </span>');
                                }
                            }
                        });
                    }
                });

                $("input[id$='merchant_gateway_security']").on('change', function () {
                    var security_code = $(this).val();
                    var length_id = security_code.length;
                    if (length_id > 2) {
                        $.ajax ({
                            url: '<?php echo $this->getAjaxUrl() ?>',
                            showLoader: true,
                            data: {merchant:security_code, type:'security'},
                            type: "POST",
                            success: function(result) {
                                $("input[id$='merchant_gateway_security']").css('border','1px solid #adadad');
                                $('.incorrect-security').remove();
                                if (result.status == 'error') {
                                    $("input[id$='merchant_gateway_security']").css('border','1px solid red');
                                    $("input[id$='merchant_gateway_security']").closest('td').append('<span style="color:red" class="incorrect-security">SecurityCode should be type Integer, please correct. </span>');
                                }
                            }
                        });
                    }
                });
                
            });
        });
</script>