<?php
/**
 * Copyright © 2018 Cointopay. All rights reserved.
 * See COPYING.txt for license details.
 */

$order = $block->getOrder();
?>
<style type="text/css">
    .cointopay.popup-overlay{
        visibility:hidden;
        position: relative;
        background: #ffffff;
        width: 90%;
        z-index: 9;
    }
    .popup-overlay.active{
      visibility:visible;
      text-align:center;
    }
    .cointopay.popup-content {
      visibility:hidden;
    }
    .popup-content.active {
      visibility:visible;
    }
    .cointopay_details {
      width: 80%;
      display: inline-block;
    }
    .cointopay_details .remaining_amount {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .address {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .time {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .trxid {
      width: 100%;
      float: left;
      margin-top: 10px;
      text-align: left;
    }
    .cointopay_details .description {
      width:100%;
      text-align: left;
      margin-top: 6px;
      display: inline-block;
    }
    .cointopay.popup-overlay, .cointopay.popup-content {
    	z-index : 99999;
    	padding : 20px;
    	height : 50%;
    	top : 10%;
    }
</style>
<div class="checkout-success">
<?php if($order->getIncrementId()) {
	$payment_gateway_code = $order->getPayment()->getMethodInstance()->getCode();
    if ($block->getCustomerId()) { ?>
        <p><?php echo __('Your order number is: <a href="'.$this->getBaseUrl().'sales/order/view/order_id/'.$order->getId().'">'. $order->getIncrementId().'</a>') ?>
        </p>
        <?php  } else { ?>
            <p><?php echo __('Your order # is: <span>%1</span>.',$order->getIncrementId()) ?></p>
        <?php } ?>
        <?php if ($payment_gateway_code == 'cointopay_gateway') { ?>
            <p><?php echo __('Thank you for your order, please complete the payment below.') ?></p>
        <?php } else { ?>
            <p><?php echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
        <?php } ?>
        
	    <!-- Cointopay popup Content -->
        <?php if ($payment_gateway_code == 'cointopay_gateway') { ?>
	        <?php $cointopay_content = $block->getCointopayHtml(); ?>
	        <?php //if ($cointopay_content) {  $cointopay_content = $cointopay_content_data->data; 
			      if ($cointopay_content) {?>
		        <div class="popup-overlay cointopay active">
		          	<div class="popup-content cointopay active">    
                        <img src="<?php echo $this->getViewFileUrl('Cointopay_PaymentGateway::images/cointopay.gif'); ?>" />
                        <h1> PAYMENT DETAILS </h1>
			            <img src="<?= $cointopay_content->QRCodeURL ?>" alt="QR Scan Cointopay" />
			            <div class="cointopay_details">
				            <p class="remaining_amount"><strong>Amount:</strong><br>
                                <?=  $cointopay_content->Amount.' ' ?>
                                <?= strtoupper($cointopay_content->CoinName).' ' ?>
                                <img src="https://s3-eu-west-1.amazonaws.com/cointopay/img/<?= $cointopay_content->CoinName ?>_dash2.png" style="width:20px;" />
				            </p>
                            <p class="address"><strong>Address: </strong> <br> <input type="text" value="<?= $cointopay_content->coinAddress ?>"> </p>
				            <p class="time"><strong>Expiry: </strong> <br><span id="expire_time"><?= date("m/d/Y h:i:s T",strtotime("+$cointopay_content->ExpiryTime minutes")) ?></span></p>
				            <p class="trxid"><strong>Transaction ID: </strong> <br><?= $cointopay_content->TransactionID ?></p>
				            <p class="description">Make sure to send enough to cover  any coin transaction fees!</p>
				            <p class="description">Send an equal amount or more.</p>
                             <p class="description"> <a target="_blank" href="<?=  $cointopay_content->RedirectURL ?>">View Invoice details</a></p>
				            <?php /* <button class="action primary confirm_payments" id="confirm_payments">Confirm Payments</button> */ ?>
				            <input type="hidden" id="cointopay_trid" value="<?= $cointopay_content->TransactionID ?>" >
			            </div>
		          	</div>
		        </div>
            <script type="text/javascript">
                require(
                    ['jquery'],
                    function($) {
                        $(function() {
                            interval = setInterval(function() {
                                if ($('#cointopay_trid').length) {
                                    selected_coin = $('#cointopay_trid').val();
                                    $.ajax ({
                                        url: '<?php echo $block->getCoinsPaymentUrl() ?>',
                                        showLoader: true,
                                        data: {paymentaction:selected_coin, type:'status'},
                                        type: "POST",
                                        success: function(result) {
                                            if (result.status == 'paid') {
                                                $('.popup-content.cointopay').html('<h3>Thank you, your payment is received!</h3><p class="description"> <a target="_blank" href="<?=  $cointopay_content->RedirectURL ?>">View Invoice details</a></p>');
                                            } else if (result.status == 'expired') {
                                                $('.popup-content.cointopay').html('<h3>Payment time expired!</h3><p class="description"> <a target="_blank" href="<?=  $cointopay_content->RedirectURL ?>">View Invoice details</a></p>');
                                            }
											 else if (result.status == 'underpaid') {
                                                $('.popup-content.cointopay').html('<h3>You have underpaid, please pay the remaining amount or contact support!</h3><p class="description"> <a target="_blank" href="<?=  $cointopay_content->RedirectURL ?>">View Invoice details</a></p>');
                                            }
                                        }
                                    });
                                }
                            }, 10000);
                            
                            // count down time left
                            var d1 = new Date (),
                            d2 = new Date ( d1 );
                            d2.setMinutes ( d1.getMinutes() + <?= $cointopay_content->ExpiryTime ?> );
                            var countDownDate = d2.getTime();

                            // Update the count down every 1 second
                            var x = setInterval(function() {
                                if ($('#expire_time').length) {
                                    // Get todays date and time
                                    var now = new Date().getTime();
                                    
                                    // Find the distance between now an the count down date
                                    var distance = countDownDate - now;
                                    
                                    // Time calculations for days, hours, minutes and seconds
                                    var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                                    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                                    var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                                    
                                    // Output the result in an element with id="expire_time"
                                    document.getElementById("expire_time").innerHTML = days + "d " + hours + "h "
                                    + minutes + "m " + seconds + "s ";
                                    
                                    // If the count down is over, write some text 
                                    if (distance < 0) {
                                        clearInterval(x);
                                        document.getElementById("expire_time").innerHTML = "EXPIRED";
                                    }
                                }
                            }, 1000);

                        });
                    });
            </script>
			<?php } else { echo "No Cointopay data found due to empty session values"; } //} else { echo "No Cointopay Data Found"; } ?>
	    <?php } ?>
<?php } ?>
<a class="action primary" style="float: right;" href="<?= $this->getBaseUrl() ?>">Continue Shopping</a>
</div>
